import React from 'react'
import { createRoot } from 'react-dom/client'
import { FigtreeProvider, PreviewBanner } from '@metatoy/figtree-react'

// Committed tokens — bundled at build time, used in production.
// Generated by Style Dictionary from tokens/tokens.json.
import { tokens } from './tokens/generated/tokens'

/** @type {import('@metatoy/figtree-react').FigtreeConfig} */
const figtreeConfig = {
  namespace: 'my-app',
  tokens,
  preview: {
    // Preview is only enabled outside production.
    // In production this whole branch is tree-shaken by bundlers.
    enabled: import.meta.env.MODE !== 'production',

    // Where the local CLI is running.
    // Override with VITE_FIGTREE_ORIGIN env var for staging.
    origin: import.meta.env.VITE_FIGTREE_ORIGIN ?? 'http://localhost:7777',

    // How often to poll for token updates (ms). Default 1500.
    pollInterval: 1500,
  },
}

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <FigtreeProvider config={figtreeConfig}>
      <App />

      {/*
        Renders a bottom banner when a preview is active.
        Renders nothing in production (isPreview is always false).
      */}
      <PreviewBanner />
    </FigtreeProvider>
  </React.StrictMode>,
)
